CREATE DATABASE CARGUEIRO
GO

USE CARGUEIRO
GO

CREATE TABLE MAR (
    /* NO SQL SERVER O IDENTITY = AUTO_INCREMENT */
    /* (1,1) SIGNIFICA QUE COMEÇA COM 1 E INCREMENTA DE 1 EM 1 */
    IDMAR INT PRIMARY KEY IDENTITY(1,1),
    NOMEMAR VARCHAR(50)
)
GO

CREATE TABLE PAIS (
    IDPAIS INT PRIMARY KEY IDENTITY(1,1),
    NOMEPAIS VARCHAR(50),
    CONTINENTE VARCHAR(30)
)
GO


CREATE TABLE PORTO (
    IDPORTO INT IDENTITY(1,1) NOT NULL,
    ID_PAIS INT NOT NULL,
    NOMEPORTO VARCHAR(50),
    ID_MAR INT NOT NULL
)
GO

-- A TABELA PORTO TEM CHAVE PRIMARIA COMPOSTA LOGO DEVE-SE USAR ALTER TABLE
ALTER TABLE PORTO 
ADD CONSTRAINT PK_PORTO
PRIMARY KEY (IDPORTO, ID_PAIS)
GO

-- ADICIONANDO AS CHAVES ESTRANGEIRAS
ALTER TABLE PORTO
ADD CONSTRAINT FK_PORTO_PAIS
FOREIGN KEY (ID_PAIS) REFERENCES PAIS(IDPAIS)
GO

ALTER TABLE PORTO
ADD CONSTRAINT FK_PORTO_MAR
FOREIGN KEY (ID_MAR) REFERENCES MAR(IDMAR)
GO


CREATE TABLE TIPONAVIO (
    IDTIPO INT PRIMARY KEY IDENTITY(1,1),
    CASCO VARCHAR(50),
    CAPACIDADEPESO FLOAT
)
GO

ALTER TABLE TIPONAVIO
ALTER COLUMN CAPACIDADEPESO VARCHAR(50)
GO

CREATE TABLE NAVIO (
    IDNAVIO INT PRIMARY KEY IDENTITY(1,1),
    NOMENAVIO VARCHAR(50),
    PROPRIETARIO VARCHAR(50),
    ID_TIPO INT NOT NULL,
    ID_PAIS INT NOT NULL,
    ID_PORTO INT NOT NULL
)
GO

-- CRIANDO AS CHAVES ESTRANGEIRAS DE NAVIO
ALTER TABLE NAVIO
ADD CONSTRAINT FK_NAVIO_TIPO
FOREIGN KEY (ID_TIPO) REFERENCES TIPONAVIO(IDTIPO)
GO


-- A CHAVE NAVIO_PORTO INDICA O PORTO ONDE O NAVIO ESTA ATUALMENTE ATRACADO
ALTER TABLE NAVIO
ADD CONSTRAINT FK_NAVIO_PORTO
FOREIGN KEY (ID_PORTO, ID_PAIS) REFERENCES PORTO(IDPORTO, ID_PAIS)
GO


CREATE TABLE MOVIMENTONAVIO (
    IDMOVIMENTO INT IDENTITY(1,1) NOT NULL,
    ID_NAVIO INT NOT NULL,
    DATA DATE,
    HORA TIME,
    LONGITUDE VARCHAR(50),
    LATITUDE VARCHAR(50)
)
GO

ALTER TABLE MOVIMENTONAVIO 
ADD CONSTRAINT PK_MOVIMENTONVAIO
PRIMARY KEY (IDMOVIMENTO, ID_NAVIO)
GO

ALTER TABLE MOVIMENTONAVIO
ADD CONSTRAINT FK_MOVIMENTONAVIO_NAVIO
FOREIGN KEY (ID_NAVIO) REFERENCES NAVIO(IDNAVIO)
GO

CREATE TABLE PORTOVISITADO (
    IDVISITA INT IDENTITY(1,1) NOT NULL,
    ID_NAVIO INT NOT NULL,
    ID_PAIS INT NOT NULL,
    ID_PORTO INT NOT NULL,
    DATAINICIO DATE,
    DATAFIM DATE
)
GO

ALTER TABLE PORTOVISITADO 
ADD CONSTRAINT PK_PORTOVISITADO
PRIMARY KEY (IDVISITA, ID_NAVIO, ID_PAIS, ID_PORTO)
GO

ALTER TABLE PORTOVISITADO
ADD CONSTRAINT FK_PORTOVISITADO_PORTO
FOREIGN KEY (ID_PORTO, ID_PAIS) REFERENCES PORTO(IDPORTO, ID_PAIS)
GO

ALTER TABLE PORTOVISITADO
ADD CONSTRAINT FK_PORTOVISITADO_NAVIO
FOREIGN KEY (ID_NAVIO) REFERENCES NAVIO(IDNAVIO)
GO
