USE CARGUEIRO
GO

-- SELECIONANDO OS NOMES DOS NAVIOS, SEUS PROPRIETARIO E SEU TIPO
SELECT N.NOMENAVIO, N.PROPRIETARIO,
T.CASCO
FROM NAVIO AS N
INNER JOIN TIPONAVIO AS T
ON T.IDTIPO = N.ID_TIPO
GO

-- SELECIONANDO A QUANTIDADE TOTAL DE NAVIOS
SELECT COUNT(*) AS QTD_NAVIOS FROM NAVIO 
GO

-- AGRUPANDO OS NAVIOS POR TIPO EM ORDEM DECRESCENTE
SELECT T.CASCO, COUNT(T.CASCO) AS QTD_NAVIOS
FROM TIPONAVIO AS T
INNER JOIN NAVIO AS N
ON T.IDTIPO = N.ID_TIPO
GROUP BY T.CASCO
ORDER BY QTD_NAVIOS DESC
GO


-- SELECIONANDO NOME DO NAVIO, EMPRESA, CAPACIDADE APENAS DO TIPO PORTA CONTEINER
SELECT N.NOMENAVIO, N.PROPRIETARIO,
T.CASCO, T.CAPACIDADEPESO
FROM NAVIO AS N
INNER JOIN TIPONAVIO AS T
ON T.IDTIPO = N.ID_TIPO
WHERE CASCO = 'PORTA CONTEINERES'
GO

-- AGRUPANDO OS NAVIOS POR EMPRESA
SELECT PROPRIETARIO, COUNT(PROPRIETARIO) AS QTD_NAVIOS
FROM NAVIO
GROUP BY PROPRIETARIO
ORDER BY QTD_NAVIOS DESC
GO

-- SELECIONANDO OS NAVIOS, OS PROPRIETARIOS E O PAIS E PORTOS ONDE ESTAO REGISTRADOS
SELECT N.NOMENAVIO, N.PROPRIETARIO,
       P.NOMEPAIS, P.CONTINENTE
FROM NAVIO AS N
INNER JOIN PAIS AS P
ON P.IDPAIS = N.ID_PAIS
GO

-- SELECIONANDO OS PORTOS E OS PAISES A QUE PERTECEM
SELECT PO.NOMEPORTO, 
       P.NOMEPAIS
FROM PORTO AS PO
INNER JOIN PAIS AS P
ON P.IDPAIS = PO.ID_PAIS
GO

-- SELECIONANDO OS PORTOS COM MAIS NAVIOS REGISTRADOS
SELECT P.NOMEPORTO, COUNT(P.NOMEPORTO) AS QTD_NAVIOS
FROM PORTO AS P
INNER JOIN NAVIO AS N
ON P.IDPORTO = N.ID_PORTO
GROUP BY P.NOMEPORTO
ORDER BY QTD_NAVIOS DESC
GO

-- SELECIONANDO OS PORTOS COM MAIS VISITAS
SELECT P.NOMEPORTO, COUNT(P.NOMEPORTO) AS QTD_VISITAS
FROM PORTO AS P
INNER JOIN PORTOVISITADO AS PV
ON P.IDPORTO = PV.ID_PORTO
GROUP BY P.NOMEPORTO
ORDER BY QTD_VISITAS DESC
GO

-- SELECIONANDO AS VISITAS MAIS LONGAS, EM DIAS, COM SEUS RESPECTIVOS NAVIOS E PORTOS
SELECT N.NOMENAVIO, N.PROPRIETARIO,
P.NOMEPORTO,
CAST(DATEDIFF(day, PV.DATAINICIO, PV.DATAFIM) AS VARCHAR) + ' DIAS' AS DURACAO_VISITA
FROM NAVIO AS N
INNER JOIN PORTOVISITADO AS PV
ON N.IDNAVIO = PV.ID_NAVIO
INNER JOIN PORTO AS P
ON P.IDPORTO = PV.ID_PORTO
ORDER BY DURACAO_VISITA DESC
GO


-- GERANDO UMA VIEW DE VISITAS A PORTOS COM NOME DO NAVIO, NOME DA EMPRESA, NOME DO PAIS, NOME DO PORTO E DATA DO INICIO E FIM DA VISITA
CREATE VIEW RELATORIO_VISITAS AS
SELECT N.NOMENAVIO, N.PROPRIETARIO,
       PA.NOMEPAIS, PO.NOMEPORTO,
       PV.DATAINICIO, PV.DATAFIM
FROM NAVIO AS N
INNER JOIN PORTOVISITADO AS PV
ON N.IDNAVIO = PV.ID_NAVIO
INNER JOIN PORTO AS PO
ON PO.IDPORTO = PV.ID_PORTO
INNER JOIN PAIS AS PA
ON PA.IDPAIS = PV.ID_PAIS
GO

SELECT * FROM RELATORIO_VISITAS
GO